spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库url
    url: jdbc:mysql://localhost:3306/testone?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: '{cipher}7888810b2f777c601bb4133e44da0dbeb5fac63f7105e951f2ad508be3feaea8'
#mybatis配置
mybatis:
  #  typeAliasesPackage: com.example.mybaitsxml.dao.entity
  mapperLocations: classpath:mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml
data:
  env: jiami
  user:
    username: eureka-client-user
    password: 99999

